### ISSUE TITLE
Manifest configuration

### ISSUE THREAD

**Issue by jeanphibaconnais** [Zenika/slack-bot-skillz#20]
A command have to be unique, unique on all environments.

So, I think we can find a mean to change command when we install the bot on an environment. 

1/ First action, save the manifest on the projet.

2/ Second action, try to play with the .env to suffix command with this name ? Exception for production.
For example, a command "hello". 
On dev, this command became "hello-dev". On stagging "hello-stagging" and on production, "hello".

3/ Third action, impact the manifest file and deploy this file. Maybe by the Slack API ? 🤷‍♂️

 4/ Documentation of course 😃

**Comment by jeanphibaconnais** [comment]
⚠️ API in beta but it seems to available :https://api.slack.com/methods/apps.manifest.update

**Comment by MailyLehoux** [comment]
```
    const result = await app.client.apps.manifest.update({
        token: app.token,
        app_id: appId,
        manifest: manifestJSON
    })
    
```

```
TypeError: Cannot read property 'update' of undefined
    at updateManifestVersion (/home/mai-ly/Bureau/slack-bot/test/slack-bot-skillz/src/updateManifestVersion.js:13:51)
```

It seems like if doesn't existing ⚰️

**Comment by MailyLehoux** [comment]
Some documentation has been added : https://docs.google.com/document/d/1VNHepiCHvmf6mLz2AZmaUNJzSKHFuQS4N2nUNNzKepY/edit#heading=h.by9bwbmfpzmk
