### ISSUE TITLE
Hasura schema tables

### ISSUE THREAD

**Issue by MailyLehoux** [Zenika/slack-bot-skillz#29]
With Yasmine we detected an issue link to the issue #25.  

![Capture d’écran de 2022-03-10 10-26-40](https://user-images.githubusercontent.com/85115963/157633984-e0d29d90-6395-4740-ba06-77a502ab965c.png)

When we note a skill which is not updated at the today date, it will insert a new line on the database cause we have "created_at" as foreign key ?

![Capture d’écran de 2022-03-10 10-27-34](https://user-images.githubusercontent.com/85115963/157633395-b397169d-73ae-42cb-bfcb-2bae55ff0923.png)

We can't modify any fields on Hasura cause datas are already dupplicated. We are asking what is the best way to resolve this kind of issue. Should we "rework" the database schema ? A kind of "historic" with the last notes is it usefull ?

**Comment by jeanphibaconnais** [comment]
Hello 👋, When you said 

_When we note a skill which is not updated at the today date, [...] ?_

You can note a skill with another date that today ?

**Comment by MailyLehoux** [comment]
@jeanphibaconnais Yes it's a kind of historic. If you note a skill in Februrary and in March, in base you will create 2lines of the differents dates that you had noted a skill.


In Skillz Web App this is the way to save the skills, it use "create_columns" and no "udpate_columns"
