### ISSUE TITLE
Recurrency : automatic message

### ISSUE THREAD

**Issue by MailyLehoux** [Zenika/slack-bot-skillz#4]
The bot should send message to people who has not been connected since a long time

**Comment by MailyLehoux** [comment]
https://github.com/node-cron/node-cron can be used

**Comment by MailyLehoux** [comment]
@ebriand Do you think that 1 month for a reminder is ok ? Or we should be change this

**Comment by ebriand** [comment]
I think by default 1 month is an acceptable frequency 👍 Maybe add the possibility for users to change this value could be nice. Also maybe add a random element to prevent all the reminders to be triggered at the same time? 🤔
