### ISSUE TITLE
Update your Skillz datas - init with datas known

### ISSUE THREAD

**Issue by jeanphibaconnais** [Zenika/slack-bot-skillz#7]
When we type "/note <my skill>", it will be good to init popup with my previous skill values.

**Comment by MailyLehoux** [comment]
![Capture d’écran de 2022-02-10 14-29-37](https://user-images.githubusercontent.com/85115963/153417935-6e752a30-654a-42c4-949e-61421d6e0a3e.png)

I tried to prefill with last datas, but we can't do it dynamically cause slack asks for a prefill text, but the texts (such as "1: I looked at what is was") are not saved in database. Only the levels are saved, so I imaginated a short sentence with the level at the top of the modal. 

Do you think it's clear enough with this way?

**Comment by jeanphibaconnais** [comment]
I think yes. To be sure to understand, this way will not affect the screen ?

**Comment by MailyLehoux** [comment]
It will not affect the initial options of the radio buttons indeed
