### ISSUE TITLE
Copy paste command

### ISSUE THREAD

**Issue by jeanphibaconnais** [Zenika/slack-bot-skillz#73]
When we receive a notification by the bot, it write 
```
To update theses skills easily you can use the command /skillz-note-skill [skill name] or you can note them via Skillz app
```
But to copy / past this command, we have to make a "shift + ctrl + v" to past command without form. 

Is-it linked to the bold style ?

**Comment by MailyLehoux** [comment]
Yes I think so. We could remove the bold and italic style from this sentence
